Add post metadata + like button
holyketzer/react-js-learning pull request #3
Opened 2017-10-29 02:06 UTC by holyketzer

2017-10-29 05:47 UTC, index01d requested changes
Есть небольшие замечания по поводу аккуратности

2017-10-29 05:47 UTC, index01d commented on 01-intro/homework/TextBox.js
> +  fontSize: PropTypes.string,
лучше разделить свойства для текста и для стилей. Стили завернуть в объект `style`

2017-10-29 05:47 UTC, index01d commented on 01-intro/homework/BlogItem.js
> +  const { author, created_at, updated_at, likesCount } = metadata;
created_at - snake case
likesCount - camel case

лучше придерживаться единого стиля

2017-10-29 05:47 UTC, index01d commented on 01-intro/homework/LIke.js
> +class Like extends React.Component {
что-то с названием файла не так

2017-10-29 10:03 UTC, holyketzer commented
@index01d поправил

2017-10-31 07:12 UTC, index01d approved these changes

2017-11-01 22:47 UTC, merged