Setup work env
holyketzer/react-js-learning pull request #5
Opened 2017-11-07 00:46 UTC by holyketzer

2017-11-08 13:16 UTC, index01d requested changes
1) Теперь нужно подключать файлы скриптов не из `dist/`, а из `/assets/`, для того чтобы иметь актуальную версию с HMR от webpack. Для этого в initializer'е для webpack-dev-server мы добавили `hot: true` и указали publicPath в конфигурации webpack'a.

Поправь пожалуйста и я снова сделаю проверку

2017-11-08 13:53 UTC, holyketzer commented
@index01d ага понял, но это надо было догадаться

2017-11-09 09:25 UTC, index01d requested changes
1) Давай удалим директорию _lessons, она нам далее не понадобится
2) Нужно привести все компоненты к JSX, т.к. сейчас получился разнобой (где-то non-JSX, где-то JSX)
3) запуск `./node_modules/eslint/bin/eslint.js src/.` не должен возвращать ошибок
4) желательно внешний вид еще привести в порядок, чтобы ничего ни к чему не липло (но это так, пожелание про аккуратность)

2017-11-11 06:37 UTC, index01d approved these changes

2017-11-11 10:10 UTC, merged