Redux
holyketzer/react-js-learning pull request #7
Opened 2017-11-18 00:23 UTC by holyketzer

2017-11-18 18:29 UTC, index01d requested changes
Нужно выделить BlogListContainer, LikeContainer и PaginationContainer

2017-11-18 18:29 UTC, index01d commented on src/App.js
> +      _.assign(state.params, match.params);
лучше импортировать конкретные функции, тогда в результате treeShaking в итоговый bundle будет собираться не вся библиотека, а запись здесь будет короче (просто `assign`, вместо `_.assign`)

2017-11-18 18:29 UTC, index01d commented on src/App.js
> +      _.assign(state.params, match.params);
`import { assign } from 'lodash'`

2017-11-18 18:29 UTC, index01d commented on src/actions/Post.js
> +export const handleLike = (id) => (
должен быть один action для постановки лайка, его можно обработать в нескольких редьюсерах

2017-11-18 18:29 UTC, index01d commented on src/actions/Posts.js
> +const incrementLikes = (id) => ({
должен быть только один тип action'a (см выше)

2017-11-18 18:29 UTC, index01d commented on src/components/Posts.js
> +    this.state = { page: 1, pageCount: 0 };
лучше унести в redux-состояние, втч и потому что обычно эти данные будут приходить с сервера.

2017-11-18 18:29 UTC, index01d commented on src/components/Posts.js
> +          <BlogList items={items} onLike={this.props.onLike}/>
лучше выделить BlogListContainer, LikeContainer (оформить как react-redux контейнеры), чтобы не носить функцию `onLike` по иерархии

2017-11-18 18:29 UTC, index01d commented on src/containers/PostContainer.js
> +  onLike: () => dispatch(handleLike(props.match.params.id))
должно быть в LikeContainer'e

2017-11-18 18:29 UTC, index01d commented on src/containers/PostsContainer.js
> +  items: state.posts.entries,
здесь можно сделать выборку в соответствии с состоянием пейджинации, которое лучше у нести в единое redux-состояние

2017-11-18 18:29 UTC, index01d commented on src/containers/PostsContainer.js
> +  onLike: (id) => dispatch(handleLike(id))
должно быть в LikeContainer

2017-11-21 06:30 UTC, index01d requested changes
actionCreator Like'a лучше вынести в отдельный модуль `actions/Like`;

Нужно выделить, как минимум LikeContainer

2017-11-21 06:30 UTC, index01d commented on src/components/Posts.js
> +    const columns = map(
похоже, что не используется?

2017-11-21 06:30 UTC, index01d commented on src/containers/PostsContainer.js
> +  onLike: (id) => dispatch(handleLike(id)),
должно быть в LikeContainer'e

2017-11-21 06:30 UTC, index01d commented on src/containers/PostsContainer.js
> +  onPageChange: (page) => dispatch(postsPageChange(page)),
должно быть в PaginationContainer'e

2017-11-21 06:30 UTC, index01d commented on src/containers/PostsContainer.js
> +  pagination: state.posts.pagination,
лучше вынести PaginationContainer

2017-11-21 11:12 UTC, holyketzer commented on src/components/Posts.js
> +    const columns = map(
Похоже что используется, иначе линтер бы ругался

2017-11-23 11:38 UTC, index01d approved these changes

2017-11-23 11:38 UTC, index01d commented on src/components/widgets/blog/Item.js
> +      <LikeContainer likesCount={likesCount} postId={id} />
likesCount можно получить в контейнере из state, здесь можно оставить просто id (название postId как-то избыточно в таком контексте)

2017-11-23 12:47 UTC, merged